[package]
name = "catapult"
version = "0.1.1"
authors = ["Nathaniel Emerson <nath.emerson@drakon.io>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = "0.5.0-rc.2"
